name: "validate-genezio-github-action"
on:
  push:
    branches:
      - main
      - "releases/*"
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'
  schedule:
    - cron: 0 0 * * 1

jobs:
  stable:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup genezio
        uses: ./
      - name: Verify genezio installation
        run: genezio --version
